### ISSUE TITLE
not able to run jetty-hightide-7.2.0.v20101020 

### ISSUE THREAD

**Issue by epishkin** [codebrewer/intellij-idea-jetty-integration-plugin#4]
I can reproduce this issue in IDEA 9.0.3 and IDEA X 98.231. jetty6 works properly. For jetty7 I get the following eror:

> /Users/oleksii/Library/Application Support/IntelliJIdea10/JettyIntegration/bin/jetty.sh /Users/oleksii/projects/bin/jetty-hightide-7.2.0.v20101020/etc/jetty.xml /Users/oleksii/Library/Caches/IntelliJIdea10/jetty_b368383/context-deployer.xml
> 
> 58525
> 
> STOP.KEY=1gk67u67d4w00
> 
> java.lang.IllegalArgumentException: No such OPTIONS: jdbc
> 
>   at org.eclipse.jetty.start.Config.getCombinedClasspath(Config.java:400)
>   at org.eclipse.jetty.start.Config.getActiveClasspath(Config.java:377)
>   at org.eclipse.jetty.start.Main.start(Main.java:536)
>   at org.eclipse.jetty.start.Main.parseCommandLine(Main.java:280)
>   at org.eclipse.jetty.start.Main.main(Main.java:82)
> 
> Use java -jar start.jar --help for usage information.
> 
> Disconnected from server

**Comment by codebrewer** [comment]
Closing this issue as the repository is being archived to discourage further use.
